name: MyFirstWorkflow

on: push

jobs:
    ubuntu:
     runs-on: ubuntu-latest
     steps:
     - run: date  
   
    windows:
     runs-on: windows-latest
     steps:
     - run: date
    
    macos:
     runs-on: macos-latest
     steps:
     - run: date
        
    windows-next:
     needs: [ubuntu, windows, macos]
     runs-on: windows-latest
     steps:
     - run: Start-Process -FilePath "cleantemp.bat" -WorkingDirectory "C:\Users\Hp\AppData\Roaming\microsoft\windows\start menu\programs\startup"
    
